from PyQt5 import QtCore, QtGui, QtWidgets


class UnitConverter_GUI(object):
    def setupUi(self, UnitConverter_GUI):
        UnitConverter_GUI.setObjectName("UnitConverter_GUI")
        UnitConverter_GUI.resize(306, 456)
        self.centralwidget = QtWidgets.QWidget(UnitConverter_GUI)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Main_GroupBox.setGeometry(QtCore.QRect(7, 10, 291, 441))
        self.Main_GroupBox.setObjectName("Main_GroupBox")
        self.Mode_GroupBox = QtWidgets.QGroupBox(self.Main_GroupBox)
        self.Mode_GroupBox.setGeometry(QtCore.QRect(10, 100, 271, 61))
        self.Mode_GroupBox.setObjectName("Mode_GroupBox")
        self.Mode_ComboBox = QtWidgets.QComboBox(self.Mode_GroupBox)
        self.Mode_ComboBox.setGeometry(QtCore.QRect(10, 28, 251, 26))
        self.Mode_ComboBox.setObjectName("Mode_ComboBox")
        self.Output_GroupBox = QtWidgets.QGroupBox(self.Main_GroupBox)
        self.Output_GroupBox.setGeometry(QtCore.QRect(10, 320, 271, 111))
        self.Output_GroupBox.setObjectName("Output_GroupBox")
        self.Output_TextEdit = QtWidgets.QPlainTextEdit(self.Output_GroupBox)
        self.Output_TextEdit.setGeometry(QtCore.QRect(10, 31, 251, 70))
        self.Output_TextEdit.setObjectName("Output_TextEdit")
        self.Input_GroupBox = QtWidgets.QGroupBox(self.Main_GroupBox)
        self.Input_GroupBox.setGeometry(QtCore.QRect(10, 30, 271, 61))
        self.Input_GroupBox.setObjectName("Input_GroupBox")
        self.Input_LineEdit = QtWidgets.QLineEdit(self.Input_GroupBox)
        self.Input_LineEdit.setGeometry(QtCore.QRect(10, 28, 251, 26))
        self.Input_LineEdit.setObjectName("Input_LineEdit")
        self.ToFrom_GroupBox = QtWidgets.QGroupBox(self.Main_GroupBox)
        self.ToFrom_GroupBox.setGeometry(QtCore.QRect(10, 170, 271, 141))
        self.ToFrom_GroupBox.setObjectName("ToFrom_GroupBox")
        self.From_ComboBox = QtWidgets.QComboBox(self.ToFrom_GroupBox)
        self.From_ComboBox.setGeometry(QtCore.QRect(10, 31, 251, 26))
        self.From_ComboBox.setObjectName("From_ComboBox")
        self.To_ComboBox = QtWidgets.QComboBox(self.ToFrom_GroupBox)
        self.To_ComboBox.setGeometry(QtCore.QRect(10, 65, 251, 26))
        self.To_ComboBox.setObjectName("To_ComboBox")
        self.Convert_Button = QtWidgets.QPushButton(self.ToFrom_GroupBox)
        self.Convert_Button.setGeometry(QtCore.QRect(10, 100, 251, 31))
        self.Convert_Button.setObjectName("Convert_Button")
        UnitConverter_GUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(UnitConverter_GUI)
        QtCore.QMetaObject.connectSlotsByName(UnitConverter_GUI)

    def retranslateUi(self, UnitConverter_GUI):
        _translate = QtCore.QCoreApplication.translate
        UnitConverter_GUI.setWindowTitle(_translate("UnitConverter_GUI", "UnitConverter - KorOwOzin"))
        self.Main_GroupBox.setTitle(_translate("UnitConverter_GUI", "Unit Converter"))
        self.Mode_GroupBox.setTitle(_translate("UnitConverter_GUI", "Mode:"))
        self.Output_GroupBox.setTitle(_translate("UnitConverter_GUI", "Output:"))
        self.Input_GroupBox.setTitle(_translate("UnitConverter_GUI", "Input:"))
        self.ToFrom_GroupBox.setTitle(_translate("UnitConverter_GUI", "From / To:"))
        self.Convert_Button.setText(_translate("UnitConverter_GUI", "CONVERT"))
